version: "3.8"

services:
  app:
    image: ${IMAGE_TAG:-epicsa-climate-api:latest}
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    secrets:
      - service_account_key
    volumes:
      - "./app:/app/app"
      - "./junit:/tmp/junit"

secrets:
  service_account_key:
    file: ./service-account.json
