services:
  app:
    image: ${IMAGE_TAG:-epicsa-climate-api:latest}
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    secrets:
      - service_account_key
    volumes:
      - "./junit:/tmp/junit"

secrets:
  service_account_key:
    file: ./service-account.json
######################
# Debugging
######################

# entrypoint: /bin/bash -l -c "tail -f /dev/null"
# command: tail -f /dev/null
# volumes:
#    - "./app:/app"
#    - "./service-account.json:/app/service-account.json"
