services:
  app:
    image: ${IMAGE_TAG:-epicsa-climate-api:latest}
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_SECRET_FILE: /run/secrets/postgres_secret
    ports:
      - "8000:8000"
    secrets:
      - service_account_key
      - postgres_secret
    volumes:
      - "./app:/app/app"
      - "./junit:/tmp/junit"

secrets:
  service_account_key:
    file: ./service-account.json
  postgres_secret:
    file: ./postgres-secret.json
